#install.packages("roxygen2")
#install.packages("devtools")

#load packages
suppressPackageStartupMessages(library("plyr"))
suppressPackageStartupMessages(library("dplyr"))
suppressPackageStartupMessages(library("stringr"))
suppressPackageStartupMessages(library("rvest"))
suppressPackageStartupMessages(library("httr"))
suppressPackageStartupMessages(library("methods"))
suppressPackageStartupMessages(library("qdapRegex"))
suppressPackageStartupMessages(library("purrr"))
suppressPackageStartupMessages(library("foreach"))
suppressPackageStartupMessages(library("tidytext"))
suppressPackageStartupMessages(library("tidyr"))
